spring.application.name=demo
# application configuration
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Demo
info.app.description=A Spring Boot demo app
info.app.version=1.0.0

creatorName=Alex Tran
