spring.application.name=demo
# application configuration
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
# management.endpoints.web.exposure.exclude=health, info

# security config
spring.security.user.name=alex
spring.security.user.password=tran



info.app.name=Demo
info.app.description=A Spring Boot demo app
info.app.version=1.0.0

creatorName=Alex Tran
